version: '3.8'
services:

  delio-app-nginx:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/nginx/Dockerfile
      target: develop
    image: dowhilenotdone/nginx:latest    
    container_name: delio-app-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8881:8881"
    volumes:
        - ./:/var/www
        - ./docker/config/nginx/conf.d/delioapp.conf:/etc/nginx/conf.d/default.conf:ro

  delio-app-php-fpm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/php-fpm/Dockerfile
      target: develop
    image: dowhilenotdone/php-fpm:latest
    container_name: delio-app-php-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  delio-app-mysql:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/mysql/Dockerfile
      target: develop
    image: dowhilenotdone/mysql:latest
    container_name: delio-app-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - $PWD/docker/volumes/mysql:/var/lib/mysql
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=delio_dev
      - MYSQL_USER=delio_usr
      - MYSQL_PASSWORD=delio_pw
